import pinout as gen

pins = [
    [{"type": "pin", "name": "PD7", "alt": False},
     {"type": "spacer", "name":"", "alt": False},
     {"type": "sys", "name": "NRST", "alt": False},
     {"type": "tim2", "name":"CH4", "alt": False},
     {"type": "uart", "name":"CK", "alt": True},
     {"type": "opa", "name":"OPP1", "alt": False},
    ],
    [{"type": "pin", "name": "PA1", "alt": False},
     {"type": "adc", "name":"A1", "alt": False},
     {"type": "sys", "name": "OSCI", "alt": False},
     {"type": "tim1", "name":"CH2", "alt": False},
     {"type": "spacer", "name":"", "alt": False},
     {"type": "opa", "name":"OPN0", "alt": False},
    ],
    [{"type": "pin", "name": "PA2", "alt": False},
     {"type": "adc", "name":"A0", "alt": False},
     {"type": "sys", "name": "OSCO", "alt": False},
     {"type": "tim1", "name":"CH2N", "alt": False},
     {"type": "spacer", "name":"", "alt": False},
     {"type": "opa", "name":"OPP0", "alt": False},
     {"type": "adc", "name":"ETR2", "alt": False},
    ],
    [{"type": "vss", "name": "VSS", "alt": False},
    ],
    [{"type": "pin", "name": "PD0", "alt": False},
     {"type": "spacer", "name":"", "alt": False},
     {"type": "spacer", "name": "", "alt": False},
     {"type": "tim1", "name":"CH1N", "alt": False},
     {"type": "uart", "name":"TX", "alt": True},
     {"type": "opa", "name":"OPN1", "alt": False},
     {"type": "i2c", "name":"SDA", "alt": True},
    ],
    [{"type": "vdd", "name": "VDD", "alt": False},
    ],
    [{"type": "pin", "name": "PC0", "alt": False},
     {"type": "tim2", "name":"CH3", "alt": False},
     {"type": "tim1", "name":"CH3", "alt": True},
     {"type": "spi", "name":"NSS", "alt": True},
     {"type": "uart", "name": "TX", "alt": True},
    ],
    [{"type": "pin", "name": "PC1", "alt": False},
     {"type": "i2c", "name":"SDA", "alt": False},
     {"type": "tim1", "name": "BKIN", "alt": True},
     {"type": "spi", "name":"NSS", "alt": False},
     {"type": "uart", "name":"RX", "alt": True},
     {"type": "tim2", "name":"CH4", "alt": True},
     {"type": "tim2", "name":"CH1", "alt": True},
     {"type": "tim2", "name":"ETR", "alt": True},
    ],
    [{"type": "pin", "name": "PC2", "alt": False},
     {"type": "i2c", "name":"SCL", "alt": False},
     {"type": "tim1", "name": "BKIN", "alt": False},
     {"type": "adc", "name":"ETR", "alt": True},
     {"type": "uart", "name":"RTS", "alt": False},
     {"type": "tim2", "name":"CH2", "alt": True},
     {"type": "tim1", "name":"ETR", "alt": True},
    ],
    [{"type": "pin", "name": "PC3", "alt": False},
     {"type": "spacer", "name":"", "alt": False},
     {"type": "tim1", "name": "CH3", "alt": True},
     {"type": "spacer", "name":"", "alt": False},
     {"type": "uart", "name":"CTS", "alt": True},
     {"type": "tim1", "name":"CH1N", "alt": True},
     ],
    [{"type": "pin", "name": "PC4", "alt": False},
     {"type": "adc", "name": "A2", "alt": False},
     {"type": "tim1", "name": "CH4", "alt": False},
     {"type": "sys", "name": "MCO", "alt": False},
     {"type": "tim1", "name": "CH1CH2N", "alt": True},
     ],
    [{"type": "pin", "name": "PC5", "alt": False},
     {"type": "spi", "name": "SCK", "alt": False},
     {"type": "tim1", "name": "T1ETR", "alt": False},
     {"type": "tim1", "name": "CH3", "alt": True},
     {"type": "i2c", "name": "SCL", "alt": True},
     {"type": "uart", "name": "UCK", "alt": True},
     ],
    [{"type": "pin", "name": "PC6", "alt": False},
     {"type": "spi", "name": "MOSI", "alt": False},
     {"type": "tim1", "name": "T1CH1CH3N", "alt": True},
     {"type": "spare", "name": "", "alt": False},
     {"type": "i2c", "name": "SDA", "alt": True},
     {"type": "uart", "name": "UCTS", "alt": True},
     ],
    [{"type": "pin", "name": "PC7", "alt": False},
     {"type": "spi", "name": "MISO", "alt": False},
     {"type": "tim1", "name": "T1CH2", "alt": True},
     {"type": "tim2", "name": "T2CH2", "alt": True},
     {"type": "spare", "name": "", "alt": False},
     {"type": "uart", "name": "URTS", "alt": True},
     ],
    [{"type": "pin", "name": "PD1", "alt": False},
     {"type": "adc", "name": "AETR2", "alt": False},
     {"type": "tim1", "name": "T1CH3N", "alt": False},
     {"type": "system", "name": "SWIO", "alt": False},
     {"type": "spare", "name": "SCL", "alt": True},
     {"type": "uart", "name": "URX", "alt": True},
     ],
    [{"type": "pin", "name": "PD2", "alt": False},
     {"type": "adc", "name": "A3", "alt": False},
     {"type": "tim1", "name": "T1CH1", "alt": False},
     {"type": "tim2", "name": "T2CH3", "alt": True},
     {"type": "spare", "name": "", "alt": True},
     {"type": "tim1", "name": "T1CH2N", "alt": True},
     ],
    [{"type": "pin", "name": "PD3", "alt": False},
     {"type": "adc", "name": "A4", "alt": False},
     {"type": "tim2", "name": "T2CH2", "alt": False},
     {"type": "uart", "name": "UCTS", "alt": False},
     {"type": "tim1", "name": "T1CH4", "alt": True},
     {"type": "adc", "name": "AETR", "alt": True},
     ],
    [{"type": "pin", "name": "PD4", "alt": False},
     {"type": "adc", "name": "A7", "alt": False},
     {"type": "tim2", "name": "T2CH1ETR", "alt": False},
     {"type": "uart", "name": "UCK", "alt": False},
     {"type": "tim1", "name": "T1CH4ETR", "alt": True},
     {"type": "opa", "name": "OPO", "alt": True},
     ],
    [{"type": "pin", "name": "PD5", "alt": False},
     {"type": "adc", "name": "A5", "alt": False},
     {"type": "tim2", "name": "T2CH4", "alt": True},
     {"type": "uart", "name": "UTX", "alt": False},
     {"type": "uart", "name": "URX", "alt": True},
     ],
    [{"type": "pin", "name": "PD6", "alt": False},
     {"type": "adc", "name": "A6", "alt": False},
     {"type": "tim2", "name": "T2CH3", "alt": True},
     {"type": "uart", "name": "URX", "alt": False},
     {"type": "uart", "name": "UTX", "alt": True},
     ],
    [{"type": "vss", "name": "VSS", "alt": False},
    ],
]

types = {
    "pin": {
        "borderColor": "black",
        "backgroundColor": "grey",
        "textColor": "white"
    },
    "i2c": {
        "borderColor": "#00B8CC",
        "backgroundColor": "#88EBF7",
        "textColor": "black"
    },
    "tim1": {
        "borderColor": "#00CCA0",
        "backgroundColor": "#99FFE9",
        "textColor": "black"
    },
    "tim2": {
        "borderColor": "#69CC00",
        "backgroundColor": "#DAFFB3",
        "textColor": "black"
    },
    "adc": {
        "borderColor": "#0060CD",
        "backgroundColor": "#A2CEFF",
        "textColor": "black"
    },
    "sys": {
        "borderColor": "#9600CC",
        "backgroundColor": "#E399FF",
        "textColor": "black"
    },
    "uart": {
        "borderColor": "#CC0092",
        "backgroundColor": "#FFA3E5",
        "textColor": "black"
    },
    "spi": {
        "borderColor": "#00CC5F",
        "backgroundColor": "#8CEEBA",
        "textColor": "black"
    },
    "opa": {
        "borderColor": "#CCAA00",
        "backgroundColor": "#FFE97C",
        "textColor": "black"
    },
    "vss": {
        "borderColor": "black",
        "backgroundColor": "black",
        "textColor": "white"
    },
    "vdd": {
        "borderColor": "red",
        "backgroundColor": "red",
        "textColor": "white"
    },
}

pinout = gen.Package("QFN-20", "QFN")
pinout.set_footprint(20, 40, 30, 20, 60)
pinout.set_label(80, 10, 30)
pinout.add_types(types)
pinout.add_pins(pins)

pinout.save()